[package]
name = "mtk-material"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
rust-version.workspace = true

[dependencies]
mtk-core = { workspace = true }
mtk-resource = { workspace = true }
mtk-texture = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true, optional = true }

[features]
default = ["std", "parallel"]
std = [
    "mtk-core/std",
    "mtk-resource/std",
    "mtk-texture/std",
]
parallel = [
    "dep:rayon",
    "mtk-resource/parallel",
    "mtk-texture/parallel",
]

[dev-dependencies]
