[package]
name = "libmtk"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
description = "Unified facade library for MoziToolKit core functionality."

[dependencies]
mtk-core = { workspace = true }
mtk-cull = { workspace = true }
mtk-model = { workspace = true }
mtk-voxel = { workspace = true }
mtk-resource = { workspace = true }
mtk-texture = { workspace = true }
mtk-material = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = ["std", "parallel", "sync"]
std = [
    "mtk-core/std",
    "mtk-cull/std",
    "mtk-model/std",
    "mtk-voxel/std",
    "mtk-resource/std",
    "mtk-texture/std",
    "mtk-material/std",
    "dep:bincode",
]
parallel = [
    "mtk-core/parallel",
    "mtk-model/parallel",
    "mtk-voxel/parallel",
    "mtk-resource/parallel",
    "mtk-texture/parallel",
    "mtk-material/parallel",
    "dep:rayon",
]
sync = [
    "mtk-voxel/sync",
]

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

