[package]
name = "mtk-py"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Python bindings for libmozitoolkit using PyO3."

[lib]
name = "libmtk_py"
crate-type = ["cdylib", "rlib"]

[dependencies]
libmtk = { workspace = true }
mtk-core = { workspace = true }
mtk-cull = { workspace = true }
mtk-model = { workspace = true }
mtk-resource = { workspace = true, features = ["zip"] }
mtk-texture = { workspace = true }
mtk-material = { workspace = true }
mtk-voxel = { workspace = true }
glam = { workspace = true }
pyo3 = { workspace = true, features = ["abi3-py310"] }

[features]
default = ["extension-module", "zip"]
extension-module = ["pyo3/extension-module"]
zip = ["mtk-resource/zip"]

[dev-dependencies]
pyo3 = { workspace = true, features = ["auto-initialize"] }
