pub const JMC2OBJ_BANNER_SHORT_ALIASES: &[(&str, &str)] = &[
    ("pattern_base", "entity/banner/banner_base"),
    ("pattern_bs", "entity/banner/stripe_bottom"),
    ("pattern_ts", "entity/banner/stripe_top"),
    ("pattern_ls", "entity/banner/stripe_left"),
    ("pattern_rs", "entity/banner/stripe_right"),
    ("pattern_cs", "entity/banner/stripe_center"),
    ("pattern_ms", "entity/banner/stripe_middle"),
    ("pattern_drs", "entity/banner/stripe_downright"),
    ("pattern_dls", "entity/banner/stripe_downleft"),
    ("pattern_ss", "entity/banner/small_stripes"),
    ("pattern_cr", "entity/banner/cross"),
    ("pattern_sc", "entity/banner/straight_cross"),
    ("pattern_ld", "entity/banner/diagonal_left"),
    ("pattern_rud", "entity/banner/diagonal_right"),
    ("pattern_lud", "entity/banner/diagonal_up_left"),
    ("pattern_rd", "entity/banner/diagonal_up_right"),
    ("pattern_vh", "entity/banner/half_vertical"),
    ("pattern_vhr", "entity/banner/half_vertical_right"),
    ("pattern_hh", "entity/banner/half_horizontal"),
    ("pattern_hhb", "entity/banner/half_horizontal_bottom"),
    ("pattern_bl", "entity/banner/square_bottom_left"),
    ("pattern_br", "entity/banner/square_bottom_right"),
    ("pattern_tl", "entity/banner/square_top_left"),
    ("pattern_tr", "entity/banner/square_top_right"),
    ("pattern_bt", "entity/banner/triangle_bottom"),
    ("pattern_tt", "entity/banner/triangle_top"),
    ("pattern_bts", "entity/banner/triangles_bottom"),
    ("pattern_tts", "entity/banner/triangles_top"),
    ("pattern_mc", "entity/banner/circle"),
    ("pattern_mr", "entity/banner/rhombus"),
    ("pattern_bo", "entity/banner/border"),
    ("pattern_cbo", "entity/banner/curly_border"),
    ("pattern_bri", "entity/banner/bricks"),
    ("pattern_gra", "entity/banner/gradient"),
    ("pattern_gru", "entity/banner/gradient_up"),
    ("pattern_cre", "entity/banner/creeper"),
    ("pattern_sku", "entity/banner/skull"),
    ("pattern_flo", "entity/banner/flower"),
    ("pattern_moj", "entity/banner/mojang"),
    ("pattern_glb", "entity/banner/globe"),
    ("pattern_pig", "entity/banner/piglin"),
    ("pattern_flw", "entity/banner/flow"),
    ("pattern_gus", "entity/banner/guster"),
];

pub const JMC2OBJ_BIOME_SUFFIXES: &[&str] = &[
    "-desert", "-forest", "-swamp", "-taiga", "-snow", "-ocean", "-jungle",
    "-badlands", "-savanna", "-dark_forest", "-birch_forest", "-plains",
    "-meadow", "-mangrove", "-cherry_grove", "-cold_ocean", "-warm_ocean",
    "_desert", "_forest", "_swamp", "_taiga", "_snow", "_ocean", "_jungle",
    "_badlands", "_savanna", "_dark_forest", "_birch_forest", "_plains",
    "_meadow", "_mangrove", "_cherry_grove", "_cold_ocean", "_warm_ocean",
];

pub const EXPLICIT_MATERIAL_ALIASES: &[(&str, &[&str])] = &[
    ("magma_block", &["block/magma", "block/magma_block"]),
    ("smooth_quartz", &["block/quartz_block_top", "block/quartz_block_side"]),
    ("smooth_sandstone", &["block/sandstone_top", "block/sandstone_bottom"]),
    ("smooth_red_sandstone", &["block/red_sandstone_top", "block/red_sandstone_bottom"]),
    ("smooth_basalt", &["block/smooth_basalt", "block/basalt_side"]),
    ("moss_carpet", &["block/moss_block", "block/moss_carpet"]),
    ("hay_block", &["block/hay_block_side", "block/hay_block_top"]),
    ("dried_kelp_block", &["block/dried_kelp_top", "block/dried_kelp_side"]),
    ("glowstone", &["block/glowstone"]),
    ("sea_lantern", &["block/sea_lantern"]),
    ("shroomlight", &["block/shroomlight"]),
    ("grass", &["block/short_grass", "block/grass"]),
    ("short_grass", &["block/short_grass"]),
    ("sculk_sensor", &["block/sculk_sensor_top", "block/sculk_sensor_side"]),
    ("calibrated_sculk_sensor", &["block/calibrated_sculk_sensor_top"]),
    ("chiseled_bookshelf", &["block/chiseled_bookshelf_empty", "block/chiseled_bookshelf_side"]),
    ("bell", &["entity/bell/bell_body", "entity/bell/bell"]),
    ("conduit", &["entity/conduit/base", "entity/conduit/cage"]),
    ("end_portal", &["entity/end_portal"]),
    ("lightning_rod", &["block/lightning_rod"]),
    ("tripwire", &["block/tripwire"]),
    ("tripwire_hook", &["block/tripwire_hook"]),
    ("cake", &["block/cake_top", "block/cake_side"]),
    ("crying_obsidian", &["block/crying_obsidian"]),
    ("ancient_debris", &["block/ancient_debris_side", "block/ancient_debris_top"]),
    ("skeleton_skull", &["entity/skeleton/skeleton"]),
    ("wither_skeleton_skull", &["entity/skeleton/wither_skeleton"]),
    ("zombie_head", &["entity/zombie/zombie"]),
    ("creeper_head", &["entity/creeper/creeper"]),
    ("dragon_head", &["entity/enderdragon/dragon"]),
    ("piglin_head", &["entity/piglin/piglin"]),
    ("player_head", &["entity/player/wide/steve", "entity/steve"]),
];
