[package]
name = "mtk-model"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
description = "Headless Minecraft BlockState parser and Model JSON data structures for libmtk."

[dependencies]
mtk-core = { workspace = true }
mtk-cull = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true, optional = true }

[features]
default = ["std", "parallel"]
std = ["mtk-core/std", "mtk-cull/std", "serde/std", "serde_json/std"]
parallel = ["dep:rayon"]
