[package]
name = "mtk-voxel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
description = "Section and World-level voxel storage, fluid surface calculation, ambient occlusion, and chunk mesh generator for libmtk."

[dependencies]
mtk-core = { workspace = true }
mtk-cull = { workspace = true }
mtk-model = { workspace = true }
glam = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
rayon = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["mtk-core/std", "mtk-cull/std", "mtk-model/std", "parallel"]
parallel = ["dep:rayon"]
serde = ["dep:serde", "dep:serde_json", "mtk-core/serde", "mtk-cull/serde"]

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
